apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: ipaas
    role: alert-rules
  name: nacos-rule

spec:
  groups:
    - name: nacos-down
      rules:
        - alert: nacos 服务不可用
          annotations:
            description: nacos所有节点消失
            summary: 'Instance {{ $labels.instance }} '
          expr: count(nacos_monitor{name="configCount"}) == 0
          for: 1m
          labels:
            severity: critical


