apiVersion: v1
kind: Service
metadata:

  labels:
    app: nacos-metrics
  name: nacos-metrics
spec:
  ports:
    - name: nacos-metrics
      port: 8848
      protocol: TCP
      targetPort: 8848
  sessionAffinity: None
  type: ClusterIP
