#!/bin/bash
# chkconfig:   2345 10 90
# description:  kafka
case $1 in
          start) 
              {{install_dir}}/kafka_{{kafka_version}}/bin/kafka-server-start.sh -daemon {{install_dir}}/kafka_{{kafka_version}}/config/server.properties
              ;;
          stop)
               {{install_dir}}/kafka_{{kafka_version}}/bin/kafka-server-stop.sh
              ;;
          status)
              jps
              ;;
          restart)
              {{install_dir}}/kafka_{{kafka_version}}/bin/kafka-server-stop.sh
              {{install_dir}}/kafka_{{kafka_version}}/bin/kafka-server-start.sh -daemon {{install_dir}}/kafka_{{kafka_version}}/config/server.properties
              ;;
          *)
              echo "require start|stop|status|restart"
              ;;
esac